kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: development
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
    nodeSelector:            # A node selector allows you to schedule the Pod only on nodes that match the specified label.                             
       hardware: t2-medium   # Pod scheduled on nodes with label "hardware:t2-medium".