kind: ReplicationController          # Creating a Kubernetes ReplicationController resource ( basic label selectors support equality-based selector) 
apiVersion: v1
metadata:
  name: myreplica
spec:
  replicas: 2                       # desired number of replicas for the Pod template
  selector:                         # select the Pods that this ReplicationController manages
    myname: Bhupinder Rajput                             
  template:                         # The template defines the desired specification of the Pods managed by the ReplicationController.
    metadata:
      name: testpod6
      labels:                       # selectors values need to match the labels values Specified in the pod template
        myname: Bhupinder
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]